name: Update Mensa Plan

on:
  schedule:
    - cron: '47 20,21,22,23 * * 6'
    - cron: '47 0,1,2,3,4,5 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright Browser
        run: |
          playwright install chromium

      - name: Run Mensa Parser
        run: |
          python mensa_parser.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Weekly Menu Images"
          file_pattern: "images/*.png"
